### ISSUE TITLE
Pdf sous Chrome

### ISSUE THREAD

**Issue by KerenWang** [matthiasbe/tutorat#10]
Comment ouvrir les pdf sous chrome et explorer?

**Comment by matthiasbe** [comment]
J'ai fait des recherches non concluantes. Du coup j'ai ouvert une question sur stackoverflow : http://stackoverflow.com/questions/31698822

**Comment by matthiasbe** [comment]
C'est réglé, à partir de maintenant j'éssaierais de debugger aussi sous chrome (en réalité leur plateforme de debug est bien mieux que sous mozillla :p )
