### ISSUE TITLE
Création CB

### ISSUE THREAD

**Issue by marechalh** [matthiasbe/tutorat#13]
Salut!
Je suis RM UE4 et je suis en train d'essayer de mettre notre CB de pré-rentrée sur le site. Voici mes remarques :
Sur la 1ere page de création (nom etc...)
-> au lieu d'un numéro de CB je voulais mettre pré-rentrée mais c'est pas possible (après c'est vrai que dans l'année on aura pas ce pb, sauf pour le CBG)
-> je n'arrive pas à mettre la date (04/09/2015). J'en ai essayé quelques autres mais ça n'a pas fonctionné non plus
-> Et juste la phrase en dessous :  "Laisser vide pour que le sujet ne soit pas publié" (au lieu de publier), bon voilà ^^

Et euh... en fait après c'est "page inaccessible", du coup voilà j'ai plus rien à dire. Mais au moins il y a déjà des commentaires sur la 1ere page :)

**Comment by matthiasbe** [comment]
Salut,
Pour afficher autre chose quz le numero du CB je peux mettre une case a cocher c'est rapide ;)
Tu pourrais detailler a propos des bug ? Qu'est ve qu'il se passe quand tu entre une date ? Message d'erreur ?
Et page inaccessible c'est quand tu valide le formulaire d'ajout de sujet c'est ça ? Il y a une actualisation et page inaccessible ? Tu a verfier que tu n'avais pas été déconnecté entre temps ?
Merci pour les retours en tout cas ;)

**Comment by matthiasbe** [comment]
Oublie le dernier "?"

**Comment by marechalh** [comment]
Hey!

Alors quand je rentre une date, le cadre est entouré de rouge et si, après avoir complété le reste, je clique sur “submit" il ne se passe rien.

Du coup je n’ai pas mis de date (puisqu’il est écrit qu’on peut ne pas en mettre et qu’il ne sera pas publié.

Donc après avoir complété la matière, le n° de CB, laissé vide la date et complété les notions traitées, je valide et c’est là que c’est page inaccessible, après une actualisation oui. Et voilà ce qu’il me dit. Si je fais précédent ou que je reviens sur la page d’accueil je suis toujours connectée.

J’espère t’avoir tout bien expliqué, sinon n’hésite pas!

Merci 😊

Hélène Maréchal

De : Matthias Beaupère
Envoyé : ‎samedi‎ ‎1‎ ‎août‎ ‎2015 ‎18‎:‎26
À : matthiasbe/tutorat
Cc : Hélène Maréchal

Salut,
Pour afficher autre chose quz le numero du CB je peux mettre une case a cocher c'est rapide ;)
Tu pourrais detailler a propos des bug ? Qu'est ve qu'il se passe quand tu entre une date ? Message d'erreur ?
Et page inaccessible c'est quand tu valide le formulaire d'ajout de sujet c'est ça ? Il y a une actualisation et page inaccessible ? Tu a verfier que tu n'avais pas été déconnecté entre temps ?
Merci pour les retours en tout cas ?

**Comment by matthiasbe** [comment]
En effet ils y avait quelques erreurs, maintenant corrigés. J'ai ajouter de quoi faire les cb de pré rentré et cb général. Surtout n'hésites pas à ouvrir une nouvelle issue si tu as d'autre bug/remarques/améliorations ;)

**Comment by marechalh** [comment]
Ok, super, merci !
Juste une autre remarque, c'est un détail. Du coup il apparaît CB "n°pré-rentrée", le n° peut s'enlever ?
En fait même dans le CB test d'UE2 que je vois dans l'onglet Sujets/coorigés, il est écrit "Concours blanc UE2 N°CB1"

**Comment by matthiasbe** [comment]
Je corrigerai ça pas de souci ;)
