### ISSUE TITLE
Situation

### ISSUE THREAD

**Issue by Kevin-Hakkakian** [matthiasbe/tutorat#3]
Premier bug, qui est sur un détail en fait... Pour l'équipe du tutorat, cette ligne semble obsolète car je les ai rajoutés dans les statuts. A la limite, si tu peux rajouter "Deuxième année" ou "Membre du tutorat".

**Comment by matthiasbe** [comment]
Tu penses que c'est mieux qu'il y ait 4 situations :
Primant
Doublant
Triplant
Membre du tutorat
?

**Comment by matthiasbe** [comment]
Normalement j'ai fait la modif dis moi si ça te va.
Et du coup sur le profil, les "matières attribuées" ne serait disponibles que pour les membres du tuto ?

Edit: Je l'ai fait sur le site dis moi ce que tu en penses

**Comment by Kevin-Hakkakian** [comment]
Oui merci, ce sera plus simple avec cette situation.

Kevin Hakkakian
