### ISSUE TITLE
Banque

### ISSUE THREAD

**Issue by KerenWang** [matthiasbe/tutorat#9]
pouvoir mettre les questions des Cb dans la banque. Merci!

**Comment by matthiasbe** [comment]
Du coup on part sur le fait qu'elles sont banquées dès que le CB est publié ? (1 jour après sa date de distribution)
C'est fait. Par contre pour l'instant j'ai pas encore codé l'affichage des QCMs d'entrainement (on voit juste lesquels sont dispos). Si tu as des idée de comment mettre ça en page... ;)
